a=float(input("Enter a number : "))
b=float(input("Enter a number : "))
fs= a+b
fsub= a-b
fm= a*b
fd= a/b
id= a//b
fe= a**b
imod= a%b
fa= fs/2
print("Sum =", fs)
print("Substraction =", fsub)
print("Multiplication =", fm)
print("Float Division =",fd)
print("Integer Division =", id)
print("Exponentiation =", fe)
print("Modulo Division =", imod)
print("Average =",fa)